title: Chris Pin
logo: /assets/img/github_headshot_circle.png
description: My name is Christopher Pin and I am a Certified Google Data Analyst with over 10 years of experience in digital marketing and e-commerce management. I specialize in helping fashion and luxury brands find practical business insights and uncover market trends to quickly capture opportunities and grow sales. If your company is struggling to increase sales or losing ground to online competitors, I'm here to help!
show_downloads: true
theme: jekyll-theme-minimal
