title: Chris Pin
logo: /assets/img/github_headshot_circle.png
description: Certified Google Data Analyst with over 10 years of experience in digital marketing and e-commerce management
show_downloads: true
theme: jekyll-theme-minimal
