title: Christopher Pin
logo: /assets/img/github_headshot_circle.png
description: Certified Google Data Analyst with a passion for transforming raw data into actionable insights.
show_downloads: false
theme: jekyll-theme-minimal
